server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: ms-auth
            uri: ${MS_AUTH_URI:http://localhost:8081}
            predicates:
              - Path=/api/users/**, /api/roles/**, /api/auth/**

          - id: ms-project-core
            uri: ${MS_PROJECT_CORE_URI:http://localhost:8082}
            predicates:
              - Path=/api/v1/projects/**, /api/v1/tasks/**
        default-filters:
          - PreserveHostHeader
          - RemoveRequestHeader=Cookie
springdoc:
  swagger-ui:
    urls:
      - name: ms-auth
        url: ${MS_AUTH_URI:http://localhost:8081}/v3/api-docs
      - name: ms-project-core
        url: ${MS_PROJECT_CORE_URI:http://localhost:8082}/v3/api-docs


