spring:
  cloud:
    bus:
      enabled: true
  management:
    endpoints:
      web:
        exposure:
          include: "*"
  threads:
    virtual:
      enabled: true
  profiles:
    active: default
logging:
  level:
    org:
      springframework:
        security: debug
jwt:
  private: M1_S3CR3T_3NTR0P1A_ECOMMERCE_SECRET_KEY
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSS}){red} %clr([%15.15t %X{traceId}-%X{spanId}]){green} %clr(%-5level){yellow} %clr(%logger{36}){cyan} - %msg%n"